version: "3.9"

services:
  mysql_db:
    image: mysql:8.2.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - DB_HOST=$MYSQL_HOST
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - 3306:3306
    secrets:
      - .env
    volumes:
      - ./backend/sql/database.sql:/docker-entrypoint-initdb.d/0_database.sql

  phpmyadmin:
    depends_on:
      - mysql_db
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  backend:
    image: node:20-alpine
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app/backend
    depends_on:
      - mysql_db
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    ports:
      - 8082:8081
    volumes:
      - ./backend:/app/backend/
    secrets:
      - .env
    links:
      - mysql_db
    command: sh -c "sleep 10 && npm start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app/frontend
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    links:
      - backend
    command: npm start

secrets:
  .env:
    file: .env
