version: "3.9"

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    networks:
      - mynetwork
    depends_on:
      - backend
    ports:
      - 3000:3000

  # Backend service
  backend:
    image: node:20
    container_name: backend
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend/
    command: npm start
    networks:
      - mynetwork
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    depends_on:
      - phpmyadmin
      - mysql_db
    ports:
      - 8081:8081
    secrets:
      - .env

  # MySQL service
  mysql_db:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./backend/sql/database.sql:/docker-entrypoint-initdb.d/0_database.sql
    environment:
      - MYSQL_HOST=MYSQL_HOST
      - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=MYSQL_DATABASE
      - MYSQL_USER=MYSQL_USER
      - MYSQL_PASSWORD=MYSQL_PASSWORD
    ports:
      - 3306:3306
    secrets:
      - .env

  # MySQL service
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - mysql_db
    ports:
      - 8080:80
    networks:
      - mynetwork
    environment:
      - mysql_db
      - PMA_ARBITRARY=1

networks:
  mynetwork:
    driver: bridge

secrets:
  .env:
    file: .env
